# Generated by Django 3.2.8 on 2021-10-27 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(help_text=models.CharField(blank=True, max_length=50), null=True, upload_to=pages.models.sectionImage)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(help_text=models.CharField(blank=True, max_length=50), null=True, upload_to=pages.models.productImage)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(max_length=6)),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('old', 'old')], default='new', max_length=50, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 3, 8, 47, 136623))),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.section')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(blank=True, choices=[('in progress', 'in progress'), ('arrived', 'arrived'), ('canceled', 'canceled')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('fav', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.favourite')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.order')),
            ],
        ),
    ]
